package vim9gorn

import (
	"strings"
)

const functionIndent = "  " // 2 spaces — Vim9 style

// SectionGenerator — Strategy для секцій .vimrc
type SectionGenerator interface {
	Generate() string
}

type Gorn struct {
	sections  []SectionGenerator
}

// New створює новий Gorn
func New() *Gorn {
	return &Gorn{
		sections:  make([]SectionGenerator, 0),
	}
}

// AddSection додає секцію (Strategy)
func (g *Gorn) AddSection(s SectionGenerator) {
	g.sections = append(g.sections, s)
}

// Generate — генерує повний vim9script
func (g *Gorn) Generate() string {
	var b strings.Builder
	b.WriteString("vim9script\n\n")
	b.WriteString("# Generated by vim9gorn 🔥\n")
	b.WriteString("# Do not edit manually\n\n")

	// Sections
	for _, sec := range g.sections {
		b.WriteString(sec.Generate() + "\n")
	}

	return b.String()
}

// Forge — записує результат у файл через DI
func (g *Gorn) Forge(path string, writer FileWriter) error {
	content := g.Generate()
	return writer.Write(path, content)
}
