vim9script

# Generated by vim9gorn 🔥
# Do not edit manually

vim9script
# === Variables ===
var loaded_myvimlib = 1
var myvimlib_version = "1.0.0"


# === Variables ===
g:mapleader = "<Space>"


def g:Setup()
  echom "myvimlib loaded"
enddef


def g:Toggle()
  if exists('g:loaded_myvimlib') | unlet g:loaded_myvimlib | else | Setup() | endif
enddef


nmap <leader>p :call Toggle()<CR>
command myvimlibToggle call Toggle()
