vim9script

# Generated by vim9gorn 🔥
# Do not edit manually

# === Options ===
set relativenumber
set tabstop=4
set wildmenu
set number

# === Variables ===
g:mapleader = "\<Space>"
g:maplocalleader = ','

# === Colorscheme ===
set background=dark
if has("termguicolors")
  set termguicolors
endif
syntax enable
colorscheme retrobox

highlight link Extra Comment
highlight Git guibg=#F34F29 guifg=#FFFFFF ctermbg=202 ctermfg=231
nmap <leader>vl ^v$h
nmap <silent> <esc> :nohlsearch<return>
vmap < <gv
vmap > >gv
def g:Greet()
  if str2nr(strftime("%H")) < 12
    echo "Good morning from vim9gorn 👋"
  elseif str2nr(strftime("%H")) < 18
    echo "Good afternoon from vim9gorn 👋"
  else
    echo "Good evening from vim9gorn 👋"
  endif
enddef


