vim9script

# Generated by vim9gorn 🔥
# Do not edit manually

# === Variables ===
var plugin_dir = expand('~/.vim/pack/plugins/opt')


var lspServers = [
    {
        name: 'typescriptlang',
        filetype: ['javascript', 'typescript'],
        path: 'typescript-language-server',
        args: ['--stdio'],
    },
    {
        filetype: ['go', 'gomod'],
        path: '/home/olex/prodev/go/bin/gopls',
        args: [],
    }
]
def g:CheckGit()
  if !executable('git') | echoerr 'Git is required to install plugins' | endif
enddef


def g:EnsurePluginDir()
  if !isdirectory(plugin_dir) | mkdir(plugin_dir, 'p') | endif
enddef


def g:PluginName(repo: string): string
  return fnamemodify(repo, ':t')
enddef


def g:PluginPath(repo: string): string
  return plugin_dir .. '/' .. PluginName(repo)
enddef


def g:InstallPlugin(repo: string)
  var path = PluginPath(repo)
  if !isdirectory(path)
    var url = 'https://github.com/' .. repo .. '.git' | echom 'Installing ' .. repo | system('git clone --depth 1 ' .. shellescape(url) .. ' ' .. shellescape(path))
  endif
enddef


def g:UpdatePlugin(repo: string)
  var path = PluginPath(repo)
  if isdirectory(path)
    echom 'Updating ' .. repo | system('git -C ' .. shellescape(path) .. ' pull --ff-only')
  endif
enddef


def g:LoadPlugin(repo: string)
  var name = PluginName(repo) | execute 'packadd ' .. name
enddef


# === Variables ===
g:vimsidian_vault_path = "~/prodev/MIND_VAULT"


# === Variables ===
var plugin_list = ["greeschenko/cyberpunk99.vim", "yegappan/lsp", "liuchengxu/vim-which-key", "mg979/vim-visual-multi", "SirVer/ultisnips", "honza/vim-snippets", "vim-fuzzbox/fuzzbox.vim", "greeschenko/vim9-ollama"]


def g:SetupPlugins()
  CheckGit()
  EnsurePluginDir()
  for repo in plugin_list | InstallPlugin(repo) | LoadPlugin(repo) | endfor
enddef


def g:UpdatePlugins()
  CheckGit()
  for repo in plugin_list | UpdatePlugin(repo) | endfor
enddef


command PluginsInstall call.SetupPlugins()
command PluginsUpdate call.UpdatePlugins()
# === Options ===
set hidden
set encoding=utf-8
set incsearch
set hlsearch
set expandtab
set shiftwidth=4
set ttyfast
set termguicolors
set timeoutlen=100
set wildmenu
set autoread
set noswapfile
set softtabstop=4
set smoothscroll
set autoindent
set nocursorcolumn
set nocursorline
set number
set nowrap
set clipboard=unnamed,unnamedplus
set laststatus=2
set maxmempattern=5000
set nobackup
set termencoding=utf-8
set tabstop=4
set background=dark
set smartindent


# === Colorscheme ===
set background=dark
if has("termguicolors")
  set termguicolors
endif
syntax enable
colorscheme cyberpunk99

highlight link Extra Comment
highlight Git guibg=#F34F29 guifg=#FFFFFF ctermbg=202 ctermfg=231
highlight link WarningMsg LspDiagVirtualTextWarning
highlight link WarningMsg LspDiagVirtualTextError
highlight link Comment LspDiagVirtualTextInfo
highlight link MoreMsg LspDiagVirtualTextHint
highlight link WarningMsg LspDiagSignErrorText
highlight link MoreMsg LspDiagSignWarningText
highlight link Comment LspDiagSignInfoText
highlight link MoreMsg LspDiagSignHintText
highlight link WarningMsg LspDiagInlineError
highlight link MoreMsg LspDiagInlineWarning
highlight link Comment LspDiagInlineInfo
highlight link NONE LspDiagInlineHint
# === Variables ===
g:mapleader = "\<Space>"
g:maplocalleader = ','


g:which_key_map = {}
g:which_key_map.f = { 'name': '+FZF' }
g:which_key_map.c = { 'name': '+COMMENT' }
g:which_key_map.g = { 'name': '+GIT' }
g:which_key_map.l = { 'name': '+LSP'}
g:which_key_map.l.e = { 'name': '+Diag'}
g:which_key_map.s = { 'name': '+STARGATE' }
g:which_key_map.n = { 'name': '+TREE' }
g:which_key_map.v = { 'name': '+SELECT' }
which_key#register('<Space>', "g:which_key_map", "n")
which_key#register('<Space>', "g:which_key_map_visual", "v")
nmap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
nmap <C-h> <C-w>h
nmap <C-l> <C-w>l
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <leader>vl ^v$h
nmap <silent> <esc> :nohlsearch<return>
nmap <leader>q ZZ
nmap <C-s> :w<cr>
nmap > :bn<CR>
nmap < :bp<CR>
vmap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>
vmap < <gv
vmap > >gv
nmap <leader>/ :FuzzyInBuffer<CR>
nmap <leader>b :FuzzyBuffers<CR>
nmap <leader>; :FuzzyRegisters<CR>
nmap <leader>. :FuzzyFiles<cr>
nmap <leader>fo :FuzzyMru<cr>
nmap <leader>fg :FuzzyGrep<cr>
nmap <leader>fm :FuzzyMarks<cr>
nmap <silent> <leader>lD :LspGotoDeclaration<CR>
nmap <silent> <leader>ld :LspGotoDefinition<CR>
nmap <silent> <leader>li :LspGotoImpl<CR>
nmap <silent> <leader>lt :LspGotoTypeDef<CR>
nmap <silent> <leader>lr :LspShowReferences<CR>
nmap <silent> <leader>la :LspCodeAction<CR>
nmap <silent> <leader>ln :LspRename<CR>
nmap <silent> <leader>K :LspHover<CR>
nmap <silent> <leader>len :LspDiagNext<CR>
nmap <silent> <leader>lep :LspDiagPrev<CR>
nmap <silent> <leader>lel :LspDiagShow<CR>
nmap <silent> <leader>lf :LspFormat<CR>
nmap <leader>e :Explore<CR>
def g:Main()
  SetupPlugins()
enddef


def g:LspConfig()
  call LspOptionsSet({ aleSupport: v:false, autoComplete: v:true, autoHighlight: v:false, autoHighlightDiags: v:true, autoPopulateDiags: v:false, completionMatcher: 'case', completionMatcherValue: 1, diagSignErrorText: '●', diagSignHintText: '●', diagSignInfoText: '●', diagSignWarningText: '●', echoSignature: v:false, hideDisabledCodeActions: v:false, highlightDiagInline: v:true, hoverInPreview: v:false, completionInPreview: v:false, closePreviewOnComplete: v:true, ignoreMissingServer: v:false, keepFocusInDiags: v:true, keepFocusInReferences: v:true, completionTextEdit: v:true, diagVirtualTextAlign: 'after', diagVirtualTextWrap: 'default', noNewlineInCompletion: v:false, omniComplete: v:null, omniCompleteAllowBare: v:false, outlineOnRight: v:false, outlineWinSize: 20, popupBorder: v:true, popupBorderHighlight: 'Title', popupBorderHighlightPeek: 'Special', popupBorderSignatureHelp: v:false, popupHighlightSignatureHelp: 'Pmenu', popupHighlight: 'Normal', semanticHighlight: v:true, showDiagInBalloon: v:true, showDiagInPopup: v:true, showDiagOnStatusLine: v:false, showDiagWithSign: v:true, showDiagWithVirtualText: v:true, showInlayHints: v:false, showSignature: v:true, snippetSupport: v:false, ultisnipsSupport: v:false, useBufferCompletion: v:false, usePopupInCodeAction: v:false, useQuickfixForLocations: v:false, vsnipSupport: v:false, bufferCompletionTimeout: 100, customCompletionKinds: v:false, completionKinds: {}, filterCompletionDuplicates: v:false, condensedCompletionMenu: v:false })
enddef


def g:LspServersAdd()
  call LspAddServer(lspServers)
enddef


